### PR TITLE
Use borrowed strings where possible

### PR DESCRIPTION
**Pull request by crumblingstatue**
Use Cow<str> to allow user and key to be either owned or borrowed,
reducing API friction in cases where they don't need to be owned.

Use Option<&str> for nick argument in Cleverbot::new(), as it doesn't
need to be owned.

### CODE REVIEW

**Comment by elifoster** [comment]
When does it actually need to be borrowed aside from in the README example, though? In most cases, you would only need to pass it the API User and Key (and nick if you'd like), and never need access to those values again.

**Comment by crumblingstatue** [comment]
This way is more convenient for simple uses, where the user just hardcodes the username and key into the source code with `Cleverbot::new("username", "key")`. No need to call .into() or any of that stuff.

It is also more flexible in cases the user might want to access the username and key after calling Cleverbot::new(). One could always just clone the strings, but that is less efficient than borrowing.

**Comment by elifoster** [comment]
Hardcoding api keys is bad practice anyway, so I wouldn't want to "promote" that.

And I still don't know when someone would want to access the keys after Cleverbot is initialized.

**Comment by crumblingstatue** [comment]
You got me. I can't think up any examples.
This change strictly makes things more flexible, but if that flexibility is not needed, that's okay.

I admit I mainly wanted to make the example look as nice as possible, but if you are satisfied with it, you can close this pull request.

The nick argument doesn't need to be `String` in any case though, as it is only used for communicating with the REST API, it is not stored anywhere after that. `&str` is a strictly better choice for it.

**Comment by elifoster** [comment]
I believe I actually had a good reason for making key, user, and nick all Strings rather than String Slices, but I can't remember anymore. I believe it had something to do with `fn request`.

**Comment by crumblingstatue** [comment]
The request function takes only string slices, so I doubt it's because of that function.

**Comment by elifoster** [comment]
Closing in favor of #6. I'll make the decision about changing that argument to a str within the week at some point. Gotta do some reading through the Rust book.

**Pull request closed without merging**
